create schema ERP_Financeiro;
set search_path to ERP_Financeiro;

create table ERP_Financeiro.Funcionario(
	id_funcionario int generated by default as identity primary key,
    nome varchar(100) not null,
    cpf varchar(11) unique not null,
    telefone varchar(11) unique not null,
    email varchar(100) unique not null
);

create table ERP_Financeiro.Folha_Pagamento(
	id_folha_pagamento int generated by default as identity primary key,
    descontos decimal(10, 2) not null,
    data_entrada timestamptz not null,
    horas_trabalhadas decimal(5, 2) not null,
    valor_hora decimal(6, 2) not null,
    id_funcionario int not null,
    foreign key(id_funcionario) references ERP_Financeiro.Funcionario(id_funcionario)
);

create table ERP_Financeiro.Fornecedor_Cliente(
	id_fornecedor_cliente int generated by default as identity primary key,
    razao_social_nome varchar(100) not null,
    cnpj_cpf varchar(14) unique not null,
    telefone varchar(11) unique not null,
    email varchar(100) unique not null
);

create table ERP_Financeiro.Categoria_Item(
	id_categoria_item int generated by default as identity primary key,
    nome varchar(100) not null
);

create table ERP_Financeiro.Conta_Bancaria(
	id_caixa int generated by default as identity primary key,
    nome_banco varchar(100) not null,
    numero_conta int unique
);

create table ERP_Financeiro.Forma_Pagamento(
	id_forma_pagamento int generated by default as identity primary key,
    nome varchar(100) unique not null
);

create table ERP_Financeiro.Produto(
	id_produto int generated by default as identity primary key,
    nome varchar(100) not null,
    valor decimal(8, 2) not null,
    descricao text,
    quantidade_estoque int not null,
    id_categoria_item int not null,
    foreign key(id_categoria_item) references ERP_Financeiro.Categoria_Item(id_categoria_item)
);

create type ERP_Financeiro.status_op as enum('Pendente', 'Concluída');

create table ERP_Financeiro.Operacao(
	id_operacao int generated by default as identity primary key,
    data_operacao timestamptz not null,
    status_operacao ERP_Financeiro.status_op not null,
    id_fornecedor_cliente int not null,
    foreign key(id_fornecedor_cliente) references ERP_Financeiro.Fornecedor_Cliente(id_fornecedor_cliente),
    id_funcionario int not null,
    foreign key(id_funcionario) references ERP_Financeiro.Funcionario(id_funcionario)
);

create table ERP_Financeiro.Itens_Operacao(
	id_itens_operacao int generated by default as identity primary key,
    quantidade_produtos int not null,
    id_produto int not null,
    foreign key(id_produto) references ERP_Financeiro.Produto(id_produto),
    id_operacao int not null,
    foreign key(id_operacao) references ERP_Financeiro.Operacao(id_operacao)
);

create type ERP_Financeiro.tipo_op as enum('Compra', 'Venda');

create table ERP_Financeiro.Fluxo_Caixa(
	id_fluxo_caixa int generated by default as identity primary key,
    tipo_operacao ERP_Financeiro.tipo_op not null,
    parcelas int not null,
    id_caixa int not null,
    foreign key(id_caixa) references ERP_Financeiro.Conta_Bancaria(id_caixa),

    id_forma_pagamento int not null,
    foreign key(id_forma_pagamento) references ERP_Financeiro.Forma_Pagamento(id_forma_pagamento),

    id_operacao int not null,
    foreign key(id_operacao) references ERP_Financeiro.Operacao(id_operacao),

    id_folha_pagamento int not null,
    foreign key(id_folha_pagamento) references ERP_Financeiro.Folha_Pagamento(id_folha_pagamento)
);

CREATE VIEW SaldoAtual AS
SELECT
    (
        SELECT SUM(p.valor * io.quantidade_produtos)
        FROM ERP_Financeiro.Produto p
        JOIN ERP_Financeiro.Itens_Operacao io ON p.id_produto = io.id_produto
        JOIN ERP_Financeiro.Operacao o ON o.id_operacao = io.id_operacao
        WHERE o.status_operacao = 'Concluída'
    ) - (
        SELECT SUM(fp.horas_trabalhadas * fp.valor_hora)
        FROM ERP_Financeiro.Folha_Pagamento fp
    ) AS Saldo_Total;

CREATE VIEW Valor_pVenda AS
SELECT
    io.id_operacao,
    SUM(io.quantidade_produtos * p.valor) AS valor_total
FROM ERP_Financeiro.Itens_Operacao io
JOIN ERP_Financeiro.Produto p ON io.id_produto = p.id_produto
GROUP BY io.id_operacao;

CREATE VIEW ViewNotaFiscal AS
SELECT
    fc.id_fluxo_caixa,
    o.id_operacao AS numero_nota_fiscal,

    o.data_operacao AS data_emissao, -- Adicionei a data que é fundamental para NF
    fc_cli.id_fornecedor_cliente AS id_parceiro,
    fc_cli.razao_social_nome AS nome_empresa_parceira,
    fc_cli.cnpj_cpf AS documento_parceiro,
    fc_cli.email AS email_parceiro,
    p.id_produto,
    p.nome AS nome_produto,
    io.quantidade_produtos AS quantidade,
    p.valor AS valor_unitario,
    (io.quantidade_produtos * p.valor) AS valor_total_item,
    fp.nome AS forma_pagamento,
    fc.parcelas,
    cb.nome_banco AS banco_recebimento

FROM ERP_Financeiro.Itens_Operacao io
JOIN ERP_Financeiro.Produto p ON io.id_produto = p.id_produto
JOIN ERP_Financeiro.Operacao o ON io.id_operacao = o.id_operacao
JOIN ERP_Financeiro.Fluxo_Caixa fc ON o.id_operacao = fc.id_operacao
JOIN ERP_Financeiro.Fornecedor_Cliente fc_cli ON o.id_fornecedor_cliente = fc_cli.id_fornecedor_cliente
JOIN ERP_Financeiro.Funcionario f ON o.id_funcionario = f.id_funcionario
JOIN ERP_Financeiro.Forma_Pagamento fp ON fc.id_forma_pagamento = fp.id_forma_pagamento
JOIN ERP_Financeiro.Conta_Bancaria cb ON fc.id_caixa = cb.id_caixa;

create VIEW valor_salario as
select fp.horas_trabalhadas * fp.valor_hora as salario, fp.id_funcionario
from ERP_Financeiro.Folha_Pagamento as fp;
